name: GitHub Actions Demo
run-name: Push by @${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to develop server
        uses: appleboy/ssh-action@v0.1.6
        env:
          SSH_REPOSITORY: ${{ secrets.SSH_REPOSITORY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          envs: SSH_REPOSITORY
          script: |
            cd $SSH_REPOSITORY
            git pull
            docker-compose exec -n laravel composer install
            docker-compose exec -n laravel php artisan migrate:fresh
            docker-compose exec -n laravel php artisan migrate
            docker-compose exec -n laravel php artisan db:seed
